### ISSUE TITLE
Installation Fail

### ISSUE THREAD

**Issue by Ewpratten** [PaddiM8/kalk#11]
Running `cargo install kalk_cli` is failing for me with:

```
  Updating crates.io index
  Downloaded kalk_cli v0.1.10
  Downloaded 1 crates (8.4 KB) in 0.94s
  Installing kalk_cli v0.1.10
error: failed to compile `kalk_cli v0.1.10`, intermediate artifacts can be found at `/tmp/cargo-installrPOC9T`

Caused by:
  failed to parse lock file at: /home/ewpratten/.cargo/registry/src/github.com-1ecc6299db9ec823/kalk_cli-0.1.10/Cargo.lock

Caused by:
  invalid serialized PackageId for key `package.dependencies`
```

`cargo -V` is outputting:
```
cargo 1.35.0 (6f3e9c367 2019-04-04)
```

**Comment by PaddiM8** [comment]
Ohh, looks like I forgot to update the .gitignore after changing the project structure. Does it work now, if you clone the repository and try? (I'll publish it to crates.io in that case).

**Comment by Ewpratten** [comment]
I now have this error:

```
error[E0658]: use of unstable library feature 'maybe_uninit' (see issue #53491)
   --> /home/ewpratten/.cargo/registry/src/github.com-1ecc6299db9ec823/nix-0.17.0/src/dir.rs:105:27
    |
105 |             let mut ent = std::mem::MaybeUninit::<dirent>::uninit();
    |    
```

**Comment by PaddiM8** [comment]
That's odd. I've never encountered an error like that before. What operating system are you on?

**Comment by Ewpratten** [comment]
Ubuntu x64

**Comment by matematikaadit** [comment]
It is because [`MaybeUninit` was stabilized in rust v1.36.0](https://github.com/rust-lang/rust/blob/c977b8775dd72d191ff1d8e8dceaf4b4cd5db86c/RELEASES.md#stabilized-apis-8) and it seems that you're still in v1.35.0

If you're using rustup, you can update your rust version to the latest stable channel by running `rustup update` on your terminal.

Anyway, maybe mention the minimal supported rust version on the README so that people with older rust version will know whether they need to update their compiler or not to install/build this project via cargo.

**Comment by PaddiM8** [comment]
@matematikaadit Ah, just noticed this. That makes sense, thank you.
